/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Warkarma (https://sketchfab.com/warkarma)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cabriolet-from-the-concept-6efbbf91583d420fac26038349b1c596
Title: Cabriolet from the concept
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import {useFrame, useThree} from '@react-three/fiber';
import islandScene from '../assets/3d/cabriolet_from_the_concept.glb';
import {a} from '@react-spring/three';

const Island = (props) => {
  const { nodes, materials } = useGLTF(islandScene);
  const islandRef = useRef();
  return (
    <a.group {...props} ref={islandRef}>
      <a.group rotation={[-Math.PI / 2, 0, 0]} scale={0.004}>
        <a.group rotation={[Math.PI / 2, 0, 0]}>
          <a.group rotation={[0.047, 0, 0]} scale={100}>
            <mesh
              
              
              geometry={nodes.Cabrio_Body_0.geometry}
              material={materials.Body}
            />
            <mesh
              
              
              geometry={nodes.Cabrio_Body_0_1.geometry}
              material={materials.Body}
            />
            <mesh
              
              
              geometry={nodes.Cabrio_Body_0_2.geometry}
              material={materials.Body}
            />
            <mesh
              
              
              geometry={nodes.Cabrio_Inside_0.geometry}
              material={materials.Inside}
            />
            <mesh
              
              
              geometry={nodes.Cabrio_Flames_0.geometry}
              material={materials.Flames}
            />
          </a.group>
          <a.group position={[522.108, -624.058, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Platform_Emissive_0.geometry}
              material={materials.Emissive}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Platform_Podium_0.geometry}
              material={materials.Podium}
            />
          </a.group>
        </a.group>
      </a.group>
    </a.group>
  );
}

useGLTF.preload(islandScene);

export default Island;
