/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Warkarma (https://sketchfab.com/warkarma)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cabriolet-from-the-concept-6efbbf91583d420fac26038349b1c596
Title: Cabriolet from the concept
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import {useFrame, useThree} from '@react-three/fiber';
import islandScene from '../assets/3d/desert_road.glb';
import {a} from '@react-spring/three';

const Island = (props) => {
  const { nodes, materials } = useGLTF(islandScene);
  const islandRef = useRef();
  return (
    <a.group {...props} red={islandRef}>
      <a.group scale={0.01}>
        <a.group
          position={[-43.282, 284.869, 0.712]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            geometry={nodes.body_body_0.geometry}
            material={materials.body}
          />
          <mesh
            geometry={nodes.body_body_0_1.geometry}
            material={materials.body}
          />
        </a.group>
        <a.group
          position={[-42.467, 109.268, 3.732]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            geometry={nodes.terrain_terrain_0.geometry}
            material={materials.terrain}
          />
          <mesh
            geometry={nodes.terrain_terrain_0_1.geometry}
            material={materials.terrain}
          />
        </a.group>
        <a.group
          position={[-43.282, 284.869, 0.712]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            geometry={nodes.body001outline_body001outline_0.geometry}
            material={materials.body001outline}
          />
          <mesh
            geometry={nodes.body001outline_body001outline_0_1.geometry}
            material={materials.body001outline}
          />
        </a.group>
        <a.group
          position={[-42.467, 109.268, 3.732]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            geometry={nodes.terrain001outline_terrain001outline_0.geometry}
            material={materials.terrain001outline}
          />
          <mesh
            geometry={nodes.terrain001outline_terrain001outline_0_1.geometry}
            material={materials.terrain001outline}
          />
        </a.group>
        <mesh
          geometry={nodes.sky_sky_0.geometry}
          material={materials.material}
          position={[-43.282, 284.869, 0.712]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.glass_glass_0.geometry}
          material={materials.glass}
          position={[-43.282, 284.869, 0.712]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.Object001_terrain001outline_0.geometry}
          material={materials.terrain001outline}
          position={[-42.467, 109.268, 3.732]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </a.group>
    </a.group>
  );
}

useGLTF.preload(islandScene);

export default Island;
